compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
npmPublishAccess: public
supportedArchitectures:
  cpu:
    - current
    - arm64
    - x64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32
yarnPath: .yarn/releases/yarn-4.1.0.cjs
