name: Build and check
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
env:
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
jobs:
  checks:
    name: Build and check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          cache: yarn
          node-version-file: .node-version
      - name: Install Node.js dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn turbo run build
      - name: Check
        run: yarn turbo run check
